services:
  postgres:
    image: postgres:16
    container_name: apex-drive-db
    restart: unless-stopped

    environment:
      POSTGRES_DB: apex_drive
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data: